
version: 2.1

commands:
  install-ansible:
    description: Installs Ansible
    steps:
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
  install-utility:
    description: install utility to work with workspace
    steps:
      - run:
            name: Install tar utility
            command: |
              yum install -y tar gzip

jobs:
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli:latest #check this if working or not
    steps:
      - checkout
      - install-utility
      # - run:
      #     name: Create Cloudformation Stack
      #     command: |
      #       aws cloudformation deploy \
      #         --template-file template.yml \
      #         --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
      #         --region us-east-1
      - run:
          name: get public ip of created instaces
          command: 
            touch inventory 
            echo [all] > ~/inventor.txt 
            # aws ec2 describe-instances \
            # --query 'Reservations[*].Instances[*].PublicIpAddress' \
            # --filters "Name=tag:Project,Values=udacity" \
            # --output text >> ~/inventory.txt
            cat ~/inventory.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - ~/inventory.txt


  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              fingerprints: ["27:b4:3c:a3:91:97:9a:04:5c:58:16:4b:a0:aa:1a:70"]
      - install-utility
      - attach_workspace:
          at: ~/
      - install-ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            cat ~/inventory
            ansible-playbook -i ~/inventory main.yml

workflows:
  my_workflow:
      jobs:
        - create_infrastructure
        - configure_infrastructure:
            requires:
              - create_infrastructure
